config/routes.rb
Rails.application.routes.draw do
  resources :hospitals
  resources :doctors
  resources :instructions, only: [:index]

  root 'instructions#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

  #Built in validator
  validates :last_name, :age, presence: true

  #Custom validation
  validate :doctor_minimum_age

  belongs_to :hospital

  #Helper method
  def display_name
  end

  #To fail validation
  #errors.add(:name_of_attribute, "Customer error string")
  def doctor_minimum_age
  end

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

  validates :name, presence: true

  has_many :doctors

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  before_action :check_login, only: [:edit]

  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :age, :quote)
    end


    def check_login
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name)
    end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def navbar_list_item(displayname, path, htmlopts={})
    selected = current_page?(path)
    link = link_to displayname, path, htmlopts
    "<li class=\"#{'active' if selected} \"> #{link} </li>".html_safe
  end


end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :first_name, label: "Förnamn" %>
  <%= f.input :last_name, label: "Efternamn" %>
  <%= f.input :age, label: 'Ålder' %>
  <%= f.input :quote, label: 'Inspirerande citat' %>

  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> förhindrade doctorn från att sparas:</h2>

      <ul>
        <% @doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Uppdatera doctor", class: "btn btn-success" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.display_name%></td>
        <td><%=doctor.age%></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/hospitals/_form.html.haml
= simple_form_for(@hospital, html: { class: 'form-horizontal' }) do |f|
  = f.input :name, label: "Namn"
  - if @hospital.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hospital.errors.count, "error")} prohibited this hospital from being saved:"
      %ul
        - @hospital.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/hospitals/edit.html.haml
%h1 Editing hospital

= render 'form'

= link_to 'Show', @hospital
\|
= link_to 'Back', hospitals_path

app/views/hospitals/index.html.haml
%h1 Listing hospitals

%table
  %thead
    %tr
      %th Namn
      %th
      %th
      %th

  %tbody
    - @hospitals.each do |hospital|
      %tr
        %td= hospital.name
        %td= link_to 'Show', hospital
        %td= link_to 'Edit', edit_hospital_path(hospital)
        %td= link_to 'Destroy', hospital, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Hospital', new_hospital_path

app/views/hospitals/new.html.haml
%h1 Nytt sjukhus

= render 'form'

= link_to 'Back', hospitals_path

app/views/hospitals/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_hospital_path(@hospital)
\|
= link_to 'Back', hospitals_path

app/views/instructions/index.html.haml
%h2 Länkar

%ul
  %li
    = link_to 'Ruby Syntax', 'http://www.zenspider.com/Languages/Ruby/QuickRef.html'
  %li
    = link_to 'Rails Guides', 'http://guides.rubyonrails.org/'

%h2 Översikt

%p Titta i bash fönstret, se att requests loggas.

%pre.bg-info
  cat log/development.log
  cat .gitignore
  cat config/database.yml

%p Dessa filer har inte vi skapat, de autogenererades med mycket av innehållet du ser. Ett designmål för Rails har varit "Convention over configuration".

%p Jämför med web/MVC ramverk du har tidigare erfarenhet från. Lika enkelt att komma igång? Lika enkelt att ändra conf?

%p Byt startsida från "instruktioner" till sidan som listar läkare. Det gör man i filen config/routes.rb

%p Pröva lägga till en ny sida. För det behöver du en action (i valfri existerande controller), en view samt ett entry i config/routes.rb. Pröva även länka till den nya sidan från andra sidor.

%p Tips:
%pre.bg-info
  bin/rake routes

%p Kör:

%pre.bg-info
  bin/rspec

%p Läkarna ska få en specialisering. Tips: rails generate migration. alter table, add t.string :specialization

%pre.bg-info
  bin/rake db:migrate
  bin/rake db:rollback #Om du vill ändra något
  bin/rake db:migrate

%p Observera output, kör git diff.

%p git add migration, schema. git Commit. (Schema kan kännas redundant, men: enklaste stället att kolla upp modellen, används om man vill sätta upp test db.)

%pre.bg-info
  bin/rake -T # Listar alla tasks
  bin/rails c # Starta rails console. Pröva olika finders på Doctor modellen.

%p Pröva logga in på Postgres (lösenord finns i database.yml) och lägg till fält på exvis Doctor. Starta rails console igen och hitta en existerande Doktor eller skapa en ny icke-persisterad med Doctor.new. Ditt nya värde bör synas som attribut på modellen.

%pre.bg-danger
  Fundera/diskussionsövning - hur känns det jämfört med andra web-ramverk? Modell beror på db, inte på |
  schema eller source filer. Bra/dåligt?

%h2 Validators, named scopes.

Läs på om validering, inbyggd och custom. Pröva att få failande specs angående det att gå igenom.

%h2 Named scopes

%p Skapa patienter.

%p Tips:

%pre.bg-info
  bin/rails generate scaffold patients

%p Lägg till en relation så att läkare har många patienter. Skapa ett named scope så man kan få fram läkare som inte har några patienter.

%h2 "Many to many" relation

Skapa en många till många relation, exvis mellan sjukhus och läkare.

%h2 Polymorphic belongs to

Skapa address modell. Sjukhus, läkare och patienter har address.

%h2 Heroku deployment

%p
  Heroku tillhandahåller gratis s.k "dynos" för bl.a labbar som dessa.

  %p För att kunna produktionssätta appen behöver du:

  %ul
    %li= link_to 'Herokukonto', 'https://signup.heroku.com'
    %li= link_to 'Heroku toolbelt', 'https://toolbelt.heroku.com/'

  %pre.bg-info
    = "heroku create appnamn --region eu # \"appnamn\" måste vara unikt<br/>".html_safe
    = "git push heroku master<br/>".html_safe
    = "heroku run rake db:migrate<br/>".html_safe
    = "heroku info"

  %p Appen finns tillgänglig på adressen "Web URL"

  %p= link_to 'Detaljerade instruktioner på Heroku devcenter', 'https://devcenter.heroku.com/articles/getting-started-with-rails4#deploy-your-application-to-heroku'

  %p Tips:

  %pre.bg-info
    heroku logs -t
  (visa logg på samma sätt som i utvecklingsmiljön)


%h2 Image attachments

Lägg till en profilbild för varje läkare med hjälp av
= link_to 'paperclip', 'https://github.com/thoughtbot/paperclip#quick-start'

%h2 Javascript

JQuery är inbyggt, pröva att lägga till testmetoder i helpers. Lägg till nytt javascript lib i asset-pipeline.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mejsla</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Sjukhuset</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">

                <%= navbar_list_item 'Instruktioner', instructions_path %>
                <%= navbar_list_item 'Läkare', doctors_path %>
                <%= navbar_list_item 'Sjukhus', hospitals_path %>

              </ul>
          </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
</nav>


<div id="main-container" class="container">
    <div class="row">

        <div class="col-xs-3">
            <% flash.each do |key, value| %>
                <div class="<%= flash[key] %>">
                    <%= value %>
                </div>
            <% end %>
        </div>

        <div class="col-xs-9">
            <%= yield %>
        </div>
    </div>
</div>

</body>
</html>